apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: backstage-systems
  title: for testing github actions
  description: for testing github actions
  tags:
    - actions
spec:
  owner: backstage
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        description:
          title: Description
          type: string
          description: Description of the component


  steps:
    - id: workflow_dispatch
      name: Create client API product
      action: github:actions:dispatch
      input:
        repoUrl: 'github.com?repo=venkatram&owner=venkatram8500'
        workflowId: test.yml
        branchOrTagName: master
