name: Update file and build project

on:
  workflow_dispatch: # This event allows manual triggering

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/update-file@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS }}
          path: README.md
          content: 'Updated by update-file action'
